language: ruby
cache: bundler
script: "bundle exec rspec"
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - rbx-2.1.1
env:
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
