language: ruby
script: "bundle exec rspec"
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.1.1
env:
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.2
      env: "RAILS_VERSION=master"
    - rvm: 1.9.2
      env: "RAILS_VERSION=4.0.0"
